2018-02-27 23:42:59,677 INFO werkzeug  * Detected change in '/var/www/flask_graphql/schema.py', reloading
2018-02-27 23:42:59,753 INFO werkzeug  * Restarting with stat
2018-02-27 23:43:05,440 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-27 23:43:07,445 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9310>
2018-02-27 23:43:10,448 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9550>
2018-02-27 23:43:13,451 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9090>
2018-02-27 23:43:13,451 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9090>
2018-02-27 23:43:13,451 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9090>
2018-02-27 23:43:13,452 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f9a483f9090>
2018-02-27 23:43:13,452 ERROR schema subscribe ok
2018-02-27 23:43:13,452 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-27 23:43:21,458 INFO werkzeug 127.0.0.1 - - [27/Feb/2018 23:43:21] "POST /graphql? HTTP/1.1" 200 -
2018-02-27 23:43:38,924 INFO werkzeug  * Detected change in '/var/www/flask_graphql/schema.py', reloading
2018-02-27 23:43:38,955 INFO werkzeug  * Restarting with stat
2018-02-27 23:43:39,730 WARNING werkzeug  * Debugger is active!
2018-02-27 23:43:39,732 INFO werkzeug  * Debugger PIN: 773-056-854
2018-02-27 23:43:45,905 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-27 23:43:47,907 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990210>
2018-02-27 23:43:50,909 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990450>
2018-02-27 23:43:53,912 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990090>
2018-02-27 23:43:53,912 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990090>
2018-02-27 23:43:53,913 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990090>
2018-02-27 23:43:53,913 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1b1e990090>
2018-02-27 23:43:53,914 INFO werkzeug 127.0.0.1 - - [27/Feb/2018 23:43:53] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:11:11,301 INFO werkzeug  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2018-02-28 00:11:11,302 INFO werkzeug  * Restarting with stat
2018-02-28 00:11:11,953 WARNING werkzeug  * Debugger is active!
2018-02-28 00:11:11,954 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:11:21,223 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:11:21] "GET /graphql HTTP/1.1" 200 -
2018-02-28 00:11:22,201 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:11:22] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:11:41,318 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:11:41] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:11:41,577 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:11:41] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:15:16,696 DEBUG geventwebsocket.handler Initializing WebSocket
2018-02-28 00:15:16,696 DEBUG geventwebsocket.handler Validating WebSocket request
2018-02-28 00:15:16,696 DEBUG geventwebsocket.handler Attempting to upgrade connection
2018-02-28 00:15:16,696 DEBUG geventwebsocket.handler Protocol allowed: graphql-ws
2018-02-28 00:15:16,697 DEBUG geventwebsocket.handler WebSocket request accepted, switching protocols
2018-02-28 00:15:16,699 ERROR __main__ ok1
2018-02-28 00:15:16,701 ERROR __main__ <geventwebsocket.websocket.WebSocket object at 0x7f1e43d76db0>
2018-02-28 00:15:16,707 DEBUG Rx Observable.timer(duetime=3000, period=3000)
2018-02-28 00:15:16,709 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:15:18,712 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:21,714 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:24,717 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:24,717 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:24,717 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:24,717 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43525978>
2018-02-28 00:15:24,718 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:15:27,907 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:15:27] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:15:28,491 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:15:28,508 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:15:28] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:15:29,726 ERROR __main__ ssssssssssssss
2018-02-28 00:15:29,726 ERROR __main__ Socket is dead
2018-02-28 00:15:29,726 DEBUG geventwebsocket.handler Failed to write closing frame -> closing socket
2018-02-28 00:15:29,726 DEBUG geventwebsocket.handler Closed WebSocket
2018-02-28 00:15:50,068 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:15:50] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:15:50,579 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:15:50,584 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:15:50] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:16:14,618 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:16:14] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:17:08,908 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:17:08] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:17:09,496 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:17:09,499 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:17:09] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:19:47,064 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:19:47,288 INFO werkzeug  * Restarting with stat
2018-02-28 00:19:48,631 WARNING werkzeug  * Debugger is active!
2018-02-28 00:19:48,631 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:19:51,279 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:19:51] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:19:51,821 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'limit'
2018-02-28 00:19:51,824 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:19:51] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:20:08,230 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:20:08,453 INFO werkzeug  * Restarting with stat
2018-02-28 00:20:09,604 WARNING werkzeug  * Debugger is active!
2018-02-28 00:20:09,608 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:20:17,360 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:20:17] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:20:17,840 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'limit'
2018-02-28 00:20:17,847 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:20:17] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:20:43,634 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:20:43,731 INFO werkzeug  * Restarting with stat
2018-02-28 00:20:44,882 WARNING werkzeug  * Debugger is active!
2018-02-28 00:20:44,883 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:20:49,836 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:20:49] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:20:50,518 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:20:50] "POST /graphql HTTP/1.1" 400 -
2018-02-28 00:21:35,560 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:21:35,826 INFO werkzeug  * Restarting with stat
2018-02-28 00:21:37,376 WARNING werkzeug  * Debugger is active!
2018-02-28 00:21:37,376 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:21:48,147 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:21:48] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:22:04,402 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:22:04,622 INFO werkzeug  * Restarting with stat
2018-02-28 00:22:06,003 WARNING werkzeug  * Debugger is active!
2018-02-28 00:22:06,009 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:22:08,094 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:22:08,324 INFO werkzeug  * Restarting with stat
2018-02-28 00:22:09,796 WARNING werkzeug  * Debugger is active!
2018-02-28 00:22:09,796 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:22:26,625 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:22:26] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:22:36,960 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:22:36] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:22:37,516 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:22:37,521 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:22:37] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:23:20,130 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:23:20,348 INFO werkzeug  * Restarting with stat
2018-02-28 00:23:21,604 WARNING werkzeug  * Debugger is active!
2018-02-28 00:23:21,605 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:23:24,127 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:23:24] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:23:35,671 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:23:35] "OPTIONS /graphql HTTP/1.1" 200 -
2018-02-28 00:23:36,277 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:23:36,279 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:23:36] "POST /graphql HTTP/1.1" 200 -
2018-02-28 00:24:59,818 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:24:59] "GET /graphql HTTP/1.1" 200 -
2018-02-28 00:25:01,076 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:25:01] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:25:23,157 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:25:23,397 INFO werkzeug  * Restarting with stat
2018-02-28 00:25:24,824 WARNING werkzeug  * Debugger is active!
2018-02-28 00:25:24,827 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:25:27,618 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:25:27] "GET /graphql? HTTP/1.1" 200 -
2018-02-28 00:25:28,594 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:25:28] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:25:56,920 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:25:56,925 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:25:56] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:27:23,408 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:27:23,648 INFO werkzeug  * Restarting with stat
2018-02-28 00:27:25,080 WARNING werkzeug  * Debugger is active!
2018-02-28 00:27:25,087 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:27:30,347 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:30] "GET /graphql HTTP/1.1" 200 -
2018-02-28 00:27:31,860 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:31] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:27:33,744 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() got an unexpected keyword argument 'like_message'
2018-02-28 00:27:33,747 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:33] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:27:43,633 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:27:43,759 INFO werkzeug  * Restarting with stat
2018-02-28 00:27:44,612 WARNING werkzeug  * Debugger is active!
2018-02-28 00:27:44,618 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:27:56,211 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:56] "GET /graphql HTTP/1.1" 200 -
2018-02-28 00:27:57,140 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:57] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:27:58,760 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:27:58] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:28:31,060 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:28:31,252 INFO werkzeug  * Restarting with stat
2018-02-28 00:28:32,196 WARNING werkzeug  * Debugger is active!
2018-02-28 00:28:32,204 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:28:34,665 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:28:34] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:28:35,576 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:28:35] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:28:35,759 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:28:35] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:29:37,038 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
TypeError: resolve_all_messages() missing 2 required positional arguments: 'context' and 'info'
2018-02-28 00:29:37,042 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:29:37] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:29:57,482 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:29:57,756 INFO werkzeug  * Restarting with stat
2018-02-28 00:29:58,893 WARNING werkzeug  * Debugger is active!
2018-02-28 00:29:58,894 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:29:58,917 ERROR schema query error
2018-02-28 00:29:58,919 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:29:58] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:30:30,132 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:30:30] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:32:24,099 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:32:24,336 INFO werkzeug  * Restarting with stat
2018-02-28 00:32:25,517 WARNING werkzeug  * Debugger is active!
2018-02-28 00:32:25,518 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:32:41,321 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:32:41] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:32:48,160 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:32:48] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:32:54,805 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:32:54] "POST /graphql? HTTP/1.1" 400 -
2018-02-28 00:33:00,120 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:33:00] "GET /graphql? HTTP/1.1" 200 -
2018-02-28 00:33:00,782 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:33:00] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:33:46,176 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:33:46,422 INFO werkzeug  * Restarting with stat
2018-02-28 00:33:47,676 WARNING werkzeug  * Debugger is active!
2018-02-28 00:33:47,677 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:33:49,456 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:33:49] "GET /graphql HTTP/1.1" 200 -
2018-02-28 00:33:50,288 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:33:50] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:34:05,832 ERROR schema query error
2018-02-28 00:34:05,846 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:34:05] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:34:30,942 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:34:31,205 INFO werkzeug  * Restarting with stat
2018-02-28 00:34:32,374 WARNING werkzeug  * Debugger is active!
2018-02-28 00:34:32,374 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:34:33,195 ERROR schema query error
2018-02-28 00:34:33,217 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:34:33] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:34:34,256 ERROR schema query error
2018-02-28 00:34:34,266 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:34:34] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:34:42,644 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:34:42,832 INFO werkzeug  * Restarting with stat
2018-02-28 00:34:43,683 WARNING werkzeug  * Debugger is active!
2018-02-28 00:34:43,688 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:34:55,706 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:34:55] "GET /graphql? HTTP/1.1" 200 -
2018-02-28 00:34:56,842 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:34:56] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:35:08,815 ERROR schema query error
2018-02-28 00:35:08,828 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:35:08] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:35:31,383 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphene_sqlalchemy/fields.py", line 34, in connection_resolver
    iterable = resolver(root, info, **args)
TypeError: resolve_all_messages() got an unexpected keyword argument 'last'
2018-02-28 00:35:31,386 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:35:31] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:36:47,599 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:36:47,820 INFO werkzeug  * Restarting with stat
2018-02-28 00:36:49,198 WARNING werkzeug  * Debugger is active!
2018-02-28 00:36:49,201 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:36:49,818 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphene_sqlalchemy/fields.py", line 34, in connection_resolver
    iterable = resolver(root, info, **args)
TypeError: resolve_all_messages() got an unexpected keyword argument 'last'
2018-02-28 00:36:49,823 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:36:49] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:36:55,991 ERROR graphql.execution.executor An error occurred while resolving field Query.allMessages
Traceback (most recent call last):
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executor.py", line 311, in resolve_or_error
    return executor.execute(resolve_fn, source, info, **args)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphql/execution/executors/sync.py", line 7, in execute
    return fn(*args, **kwargs)
  File "/var/www/python3_flask_graphql/py3env/lib/python3.5/site-packages/graphene_sqlalchemy/fields.py", line 34, in connection_resolver
    iterable = resolver(root, info, **args)
TypeError: resolve_all_messages() missing 2 required positional arguments: 'context' and 'info'
2018-02-28 00:36:55,993 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:36:55] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:37:08,837 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:37:09,061 INFO werkzeug  * Restarting with stat
2018-02-28 00:37:10,154 WARNING werkzeug  * Debugger is active!
2018-02-28 00:37:10,161 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:37:10,266 ERROR schema query error
2018-02-28 00:37:10,287 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:37:10] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:34,830 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:38:35,012 INFO werkzeug  * Restarting with stat
2018-02-28 00:38:35,891 WARNING werkzeug  * Debugger is active!
2018-02-28 00:38:35,897 INFO werkzeug  * Debugger PIN: 284-689-413
2018-02-28 00:38:41,664 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:41,672 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:41] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:41,878 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:41,883 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:41] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:42,047 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:42,053 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:42] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:42,222 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:42,227 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:42] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:42,479 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:42,485 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:42] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:47,663 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:47,670 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:47] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:47,838 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:47,844 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:47] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:48,015 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:48,019 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:48] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:48,182 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:48,189 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:48] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:48,376 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:48,383 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:48] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:38:48,715 ERROR schema <graphql.execution.base.ResolveInfo object at 0x7f1df321aa98>
2018-02-28 00:38:48,721 INFO werkzeug 127.0.0.1 - - [28/Feb/2018 00:38:48] "POST /graphql? HTTP/1.1" 200 -
2018-02-28 00:39:15,101 INFO werkzeug  * Detected change in '/var/www/python3_flask_graphql/schema.py', reloading
2018-02-28 00:39:15,243 INFO werkzeug  * Restarting with stat
2018-02-28 00:39:54,705 INFO werkzeug  * Restarting with stat
2018-02-28 00:40:09,802 INFO werkzeug  * Restarting with stat
2018-02-28 00:40:19,327 INFO werkzeug  * Restarting with stat
2018-02-28 00:41:13,592 INFO werkzeug  * Restarting with stat
2018-02-28 00:50:39,779 DEBUG geventwebsocket.handler Initializing WebSocket
2018-02-28 00:50:39,779 DEBUG geventwebsocket.handler Validating WebSocket request
2018-02-28 00:50:39,780 DEBUG geventwebsocket.handler Attempting to upgrade connection
2018-02-28 00:50:39,780 DEBUG geventwebsocket.handler Protocol allowed: graphql-ws
2018-02-28 00:50:39,780 DEBUG geventwebsocket.handler WebSocket request accepted, switching protocols
2018-02-28 00:50:39,780 ERROR __main__ ok1
2018-02-28 00:50:39,780 ERROR __main__ <geventwebsocket.websocket.WebSocket object at 0x7f1e43d832b8>
2018-02-28 00:50:39,953 DEBUG Rx Observable.timer(duetime=3000, period=3000)
2018-02-28 00:50:39,954 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:50:41,955 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43552978>
2018-02-28 00:50:44,958 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43552978>
2018-02-28 00:50:47,961 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43552978>
2018-02-28 00:50:47,961 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43552978>
2018-02-28 00:50:47,961 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d8c828>
2018-02-28 00:50:47,961 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d8c828>
2018-02-28 00:50:47,961 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:51:58,175 DEBUG geventwebsocket.handler Closed WebSocket
2018-02-28 00:51:58,175 ERROR __main__ ok2
2018-02-28 00:52:01,493 DEBUG geventwebsocket.handler Initializing WebSocket
2018-02-28 00:52:01,493 DEBUG geventwebsocket.handler Validating WebSocket request
2018-02-28 00:52:01,493 DEBUG geventwebsocket.handler Attempting to upgrade connection
2018-02-28 00:52:01,493 DEBUG geventwebsocket.handler Protocol allowed: graphql-ws
2018-02-28 00:52:01,494 DEBUG geventwebsocket.handler WebSocket request accepted, switching protocols
2018-02-28 00:52:01,494 ERROR __main__ ok1
2018-02-28 00:52:01,494 ERROR __main__ <geventwebsocket.websocket.WebSocket object at 0x7f1e43d833f0>
2018-02-28 00:52:01,649 DEBUG Rx Observable.timer(duetime=3000, period=3000)
2018-02-28 00:52:01,649 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:52:03,650 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:06,655 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:09,658 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:09,661 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:09,663 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:09,667 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562ac8>
2018-02-28 00:52:09,675 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 00:52:17,686 ERROR __main__ ssssssssssssss
2018-02-28 00:52:17,686 ERROR __main__ Socket is dead
2018-02-28 00:52:17,686 DEBUG geventwebsocket.handler Failed to write closing frame -> closing socket
2018-02-28 00:52:17,687 DEBUG geventwebsocket.handler Closed WebSocket
2018-02-28 01:31:18,227 DEBUG geventwebsocket.handler Initializing WebSocket
2018-02-28 01:31:18,263 DEBUG geventwebsocket.handler Validating WebSocket request
2018-02-28 01:31:18,263 DEBUG geventwebsocket.handler Attempting to upgrade connection
2018-02-28 01:31:18,264 DEBUG geventwebsocket.handler Protocol allowed: graphql-ws
2018-02-28 01:31:18,264 DEBUG geventwebsocket.handler WebSocket request accepted, switching protocols
2018-02-28 01:31:18,264 ERROR __main__ ok1
2018-02-28 01:31:18,264 ERROR __main__ <geventwebsocket.websocket.WebSocket object at 0x7f1e43d83250>
2018-02-28 01:31:18,270 DEBUG Rx Observable.timer(duetime=3000, period=3000)
2018-02-28 01:31:18,270 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
2018-02-28 01:31:20,520 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43562e10>
2018-02-28 01:31:23,521 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d88c88>
2018-02-28 01:31:26,524 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d88c88>
2018-02-28 01:31:26,524 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d88c88>
2018-02-28 01:31:26,524 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d88c88>
2018-02-28 01:31:26,525 ERROR schema <graphene_sqlalchemy.fields.SQLAlchemyConnectionField object at 0x7f1e43d88c88>
2018-02-28 01:31:26,525 DEBUG Rx CurrentThreadScheduler.schedule(state=None)
